### ISSUE TITLE
Nit: retention_period should be a multiple of db 'period'

### ISSUE THREAD

**Issue by Temikus** [livingdocsIO/loki#1]
From Loki docs:
```
# How far back tables will be kept before they are deleted. 0s disables
# deletion. The retention period must be a multiple of the index / chunks
# table "period" (see period_config).
[retention_period: <duration> | default = 0s]
```
So something like:
```
  retention_period: 336h
```

This is just a drive-by comment, feel free to ignore, but thought it might save you some debugging in the future.

Cheers! :)

**Comment by marcbachmann** [comment]
Thanks. I think loki even warns about that when starting it. We only use that setup in development and there we have the default configs. In general don't customize anything unless really required.
